import requests
import json
import streamlit as st
import unicodedata

# --- CONSTANTES ---
DISCORD_COLOR_RED = 13504833  # #CE1141 (Raptors Red)
DISCORD_COLOR_GOLD = 16766720 # Gold
WEBHOOK_URL = st.secrets["DISCORD_WEBHOOK"] if "DISCORD_WEBHOOK" in st.secrets else ""

# --- FONCTION DE NETTOYAGE (DATE/MOIS) ---
def normalize_month(month_str):
    """
    Normalise le nom du mois (minuscule, sans accent) pour correspondre aux clés.
    Ex: "Février" -> "fevrier"
    """
    if not isinstance(month_str, str): 
        return "Inconnu"
    month_str = month_str.lower().strip()
    normalized = unicodedata.normalize('NFD', month_str).encode('ascii', 'ignore').decode("utf-8")
    return normalized

# --- FONCTIONS GRAPHIQUES (Code Couleur Strict) ---
def get_uniform_color(score):
    """
    Retourne la couleur selon la règle stricte :
    - Moins de 20 : Rouge
    - De 20 à 39 : Gris Sombre
    - 40 et plus : Vert
    """
    try:
        s = float(score)
    except:
        return "#374151" # Gris par défaut en cas d'erreur

    if s >= 40: return "#10B981" # VERT (Succès)
    if s < 20:  return "#EF4444" # ROUGE (Carotte)
    return "#374151"             # GRIS SOMBRE (Neutre)

# --- FONCTIONS DE RAPPORT ---
def format_winners_list(winners, suffix=""):
    """
    Formate une liste de tuples (Joueur, Score) en chaîne propre.
    Exemple : [('Gabeur', 2), ('Mims', 2)] -> "**Gabeur** & **Mims** (2)"
    """
    if not winners: return "Personne."
    
    names = [f"**{w[0]}**" for w in winners]
    val = winners[0][1] 
    
    if len(names) == 1:
        return f"{names[0]} ({val}{suffix})"
    elif len(names) == 2:
        return f"{names[0]} & {names[1]} ({val}{suffix})"
    else:
        return f"{', '.join(names[:-1])} & {names[-1]} ({val}{suffix})"

def send_weekly_report_discord(report_data, dashboard_url):
    """
    Génère et envoie le rapport hebdomadaire complet (Embed Discord).
    """
    if not WEBHOOK_URL:
        return "URL Webhook manquante dans les secrets."

    meta = report_data.get('meta', {})
    podium = report_data.get('podium', [])
    stats = report_data.get('team_stats', {})
    
    # 1. PODIUM
    podium_txt = ""
    medals = ["🥇", "🥈", "🥉"]
    for p in podium:
        crown = f" (👑 Titre #{p['titles']})" if p['rank'] == 1 else ""
        podium_txt += f"{medals[p['rank']-1]} **{p['player']}** • {p['score']} pts{crown}\n"
    if not podium_txt: podium_txt = "Pas de données."

    # 2. ROTW LEADERBOARD
    rotw_txt = ""
    for idx, (p, nb) in enumerate(report_data.get('rotw_leaderboard', [])):
        rotw_txt += f"{idx+1}. **{p}** ({nb})  "
    if not rotw_txt: rotw_txt = "Aucun historique."
    
    # 3. LISTES GAGNANTS
    sniper_txt = format_winners_list(report_data.get('sniper', []), " BP")
    muraille_txt = format_winners_list(report_data.get('muraille', []), " 🥕")
    remontada_txt = format_winners_list(report_data.get('remontada', []), " pts prog.")
    sunday_txt = format_winners_list(report_data.get('sunday_clutch', []), " pts") if report_data.get('sunday_clutch') else "N/A"

    # 4. SERIES
    streaks_fields = []
    if report_data.get('streaks'):
        txt_s = ""
        for s in report_data['streaks']:
            txt_s += f"{s['msg']} **{s['player']}** : {s['val']} {s['type']} (Record : {s['record']})\n"
        streaks_fields.append({"name": "🔥 SÉRIES & DYNAMIQUES", "value": txt_s, "inline": False})
    
    # 5. TEAM PULSE
    sign = "+" if stats.get('diff', 0) > 0 else ""
    pulse_txt = f"📈 **Moyenne :** {stats.get('avg', 0):.1f} ({sign}{stats.get('diff', 0):.1f})\n"
    pulse_txt += f"🎯 **Best Picks :** {stats.get('bp', 0)}\n"
    pulse_txt += f"🛡️ **Carottes :** {stats.get('carrots', 0)}\n"
    if stats.get('clean_sheet'):
        pulse_txt += "✨ **CLEAN SHEET SEMAINE !** (Aucun score < 25)"

    embed = {
        "title": f"🦖 RAPTORS WEEKLY REPORT • SEMAINE #{meta.get('week_num', '?')}",
        "description": f"*Bilan du Lundi {meta.get('start_date', '?')} au Dimanche {meta.get('end_date', '?')}*",
        "color": DISCORD_COLOR_RED,
        "fields": [
            {"name": "🏆 LE PODIUM HEBDOMADAIRE", "value": podium_txt, "inline": False},
            {"name": "👑 COURSE AU TRÔNE (Total Titres)", "value": rotw_txt, "inline": False},
            {"name": "🎯 SNIPER HEBDO", "value": sniper_txt, "inline": True},
            {"name": "🛡️ LA MURAILLE", "value": muraille_txt, "inline": True},
            {"name": "🧗 LA REMONTADA", "value": remontada_txt, "inline": True},
        ]
    }
    
    if meta.get('has_sunday'):
        embed["fields"].insert(5, {"name": "🌅 SUNDAY CLUTCH (MVP Dimanche)", "value": sunday_txt, "inline": True})

    embed["fields"].extend(streaks_fields)
    embed["fields"].append({"name": "📊 TEAM PULSE", "value": pulse_txt, "inline": False})
    embed["footer"] = {"text": "War Room v22 • Generated by Python 🐍"}
    embed["fields"].append({"name": "", "value": f"👉 [Voir le Dashboard Complet]({dashboard_url})", "inline": False})

    payload = {"username": "Raptors Weekly", "avatar_url": "https://raw.githubusercontent.com/pedrille/dino-fant/main/basketball_discord.png", "embeds": [embed]}

    try:
        response = requests.post(WEBHOOK_URL, json=payload)
        return "success" if response.status_code in [200, 204] else f"Erreur Discord: {response.status_code}"
    except Exception as e:
        return str(e)

# --- LEGACY ---
def send_discord_webhook(day_df, pick, url): pass
